### ISSUE TITLE
Sofacy.json and Reaper.json share a report ID

### ISSUE THREAD

**Issue by HamptonJ** [pan-unit42/playbook_viewer#11]
Both Sofacy.json and Reaper.json have a report with an ID of "report--054e7551-bbbe-4e7f-b923-73fb08fa00b2". Is this intentional?

**Comment by HamptonJ** [comment]
It looks like these same two files also share a campaign id of "054e7551-bbbe-4e7f-b923-73fb08fa00b2", which looks like the same id?

**Comment by eiyuki** [comment]
> Both Sofacy.json and Reaper.json have a report with an ID of "report--054e7551-bbbe-4e7f-b923-73fb08fa00b2". Is this intentional?

This was a mistake. I have pushed changes that fix this. If you find any other issues like this, please let us know.


> It looks like these same two files also share a campaign id of "054e7551-bbbe-4e7f-b923-73fb08fa00b2", which looks like the same id?

This is intentional. From a viewer's perspective the Campaign is a single object. In the JSON two objects, a Report and a Campaign, are required to represent all of the data. In this case, the type portion of the id is distinct, while the uuid portion of the id is shared.

A uuid by itself is not a valid STIX 2.0 id. [Identifier](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_ko24ggw4eq0q)

There have been questions about this before and we are currently looking at ways to improve this in the Playbooks, but don't have any changes planned yet.

Hope this helps. Let us know if you have any other issues.

**Comment by HamptonJ** [comment]
Thanks! I will let you know if I see anything else like this.
